# ---------- Config ----------
ASSETS = ["OIL", "GOLD", "ELECTRONICS", "RICE", "PLUMBER"]
DEFAULT_TICK_SECONDS = 2
PRICE_TICK = 0.01
DEFAULT_STARTING_CASH = 10_000.0
DEFAULT_DURATION_SEC = 15 * 60
MAX_TRADE_HISTORY = 200
